
NEW_COLUMNS_TO_ADD = [  'Fecha de publicación del documento',
                        'Código del expediente',
                        'Tipo de Anuncio',
                        'Estado de la tramitación',
                        'Fecha de la adjudicación',
                        'Presupuesto del contrato sin IVA',
                        'Licitación electrónica',
                        'Resolución',
                        'Fecha de la primera publicación del documento',
                        'Fecha de la última publicación del documento',
                        'Dirección Web de licitación electrónica',

                        'Razón social',
                        'CIF/NIF',
                        'Clasificación',
                        'Es PYME',
                        'Sede Social Unión Europea',
                        'Código NUTS',
                        'Provincia',
                        'Municipio',
                        'Dirección postal',
                        'Código postal',
                        'Teléfono 1',
                        'Email',
                        'Plazo',                                   
                        'Precio sin IVA',
                        'Precio con IVA',
                        'Lugar ejecución en la Unión Europea',
                        'NUTS del lugar de ejecución',
                        'Es probable que el contrato sea objeto de subcontratación',
                        'Dirección Web',
                        'Teléfono',
                        'Nombre',
                        'Localidad',
                        'País',
                        'Correo electrónico',
                        'Órgano de recurso principal',
                        'Dirección',
                        'Web',
                        'Fecha inicio plazo',
                        'Fecha fin plazo',
                        'Precios unitarios',
                        'Concepto',
                        'CPVs'
                    ]

KEYS_TO_SPLIT = ['Resumen Adjudicación', 
                 'Empresas Licitadoras', 
                 'Datos de Adjudicación', 
                 'Otro tipo de poder', 
                 'El contrato es adjudicado por una central de compras',
                 'Obtención de documentación e información',
                 'Órgano de recurso',
                 'Entidad Impulsora',
                 'Poder Adjudicador',
                 # 'Órgano de Contratación'
                ]    